name: Build no cache
on:
  workflow_dispatch:
jobs:
  build:
    name: Build no cache job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build project
      run: ./gradlew build --no-daemon
